Mahogany-Module-Definition
Name:Filters module for Mahogany
Interface:Filters
Version:0.0
Author:Karsten Ballüder <karsten@phy.hw.ac.uk>

This module provides a filtering language for Mahogany.
It is an interpreter for a simplified algebraic language
which allows one to apply different tests and operations
to messages, like sorting, replying or moving them
automatically. THIS IS EXPERIMENTAL CODE!
