Mahogany-Module-Definition
Name:Dummy module for Mahogany
Interface:none
Version:0.0
Author:Karsten Ballüder <karsten@phy.hw.ac.uk>
Flags: 0

This module does not do anything,
it simply gets loaded, opens a dialog and
that's all. It's purpose is to serve as an
example and template for writing real modules.
