Mahogany-Module-Definition
Name: Dummy module for Mahogany
Version: 0.0
Author: Karsten Ballüder <karsten@phy.hw.ac.uk>

This module does not do anything,
it simply gets loaded, opens a dialog and
that's all. It's purpose is to serve as an
example and template for writing real modules.
