Mahogany-Module-Definition
Name:PalmOS module for Mahogany
Interface:PalmOS
Version:0.0
Author:Karsten Ballüder <karsten@phy.hw.ac.uk>
Flags:0

Provides connectivity to PalmOS based pocket computers.
