Mahogany-Module-Definition
Name:XFMail address book
Interface:AdbImporter
Version:1.00
Author:Vadim Zeitlin <vadim@wxwindows.org>
Flags: 0

Allows to import address book used by XFMail program
to Mahogany address book.
