#!/bin/sh
    sed "1,$ s/\[//g
	1,$ s/\]//g
	1,$ s/nil/\" \"/g
    1,$ s/^(\"\(.*@.*\"\))/\1/g
	1,$ s/\" \"/;/g
	1,$ s/\"//g
	1,$ s/^\"//g
	    1,$ s/(//g
		1,$ s/)//g
		1,$ s/ *//g
     "\
    |    tee out |\
	gawk '
BEGIN { 
	FS=";" 
	print "[ADB_Header]"
	print "Name = BBDB"
	print "Description = \"Imported from BBDB.\""
	print
	print "[ADB_Entries]"
}
    { 
	firstname = $1; lastname = $2; email = $6;
	if(length(email) == 0)
	    email=$5
	if(length(firstname) || length(lastname))
	{
        printf ("%s%s = %s %s:%s:%s:::::%s:::0\n",firstname,lastname, firstname, lastname,
      		firstname, lastname,email	);
	   }
    }'




