#!/bin/sh
#
# $Id$
# script to find all sources marked with FIXME

sources=`find . -type f \( -name \*.cpp -o -name \*.h -o -name \*.cc -o -name \*.c \)`
for i in $sources
do
	line=`fgrep "FIXME" $i`
	if [ $? = 0 ]
	then
		echo file: $line
	fi
done

