#!/bin/sh

MAKE="make -s"
export MAKE  
BUILDDIR=/usr/local/tmp/rpm_build
export BUILDDIR

CVSROOT=:pserver:anoncvs@wxcvs.dhs.org:/home/karsten/CVSSERVER/wxcvs
export CVSROOT
OS=`uname -s`-`uname -m`
export OS
HOST=`hostname`.`domainname`
CVS=cvs

NAME=wxGTK
VERSION=-2.1.0-b7

PREFIX=/tmp/karsten/opt

PATH=$PATH:$PREFIX/bin
    
rm -rf $BUILDDIR 
mkdir $BUILDDIR && \
cd $BUILDDIR && \
cvs checkout -A wxWindows >/dev/null 2>&1 && \
mv wxWindows $NAME && \
tar czf /usr/src/redhat/SOURCES/$NAME$VERSION.tgz $NAME && \
cp /home/karsten/bin/wxGTK.spec /usr/src/redhat/SPECS/wxGTK.spec && \
rm -rf $BUILDDIR
cd /usr/src/redhat/ && \
rpm -ba SPECS/wxGTK.spec && \
rpm -i RPMS/i386/wxGTK-2.1.0-7.i386.rpm    
mv RPMS/i386/$NAME*.rpm /home/karsten/WWW/Mahogany/daily/
mv SRPMS/$NAME*.rpm /home/karsten/WWW/Mahogany/daily/

CVSROOT=:pserver:anoncvs@wxcvs.dhs.org:/home/karsten/CVSSERVER/mcvs
NAME=mahogany
VERSION=0.23a    
rm -rf $BUILDDIR 
mkdir $BUILDDIR && \
cd $BUILDDIR && \
cvs checkout -A M >/dev/null 2>&1 && \
mv M $NAME-$VERSION && \
cp /home/karsten/WWW/Mahogany/daily/Mdocs.tar.gz $NAME-$VERSION/doc && \
tar czf /usr/src/redhat/SOURCES/$NAME-$VERSION.tar.gz $NAME-$VERSION && \
cp /home/karsten/bin/M.spec /usr/src/redhat/SPECS/M.spec && \
cp $BUILDDIR/$NAME/redhat/mahogany.gif /usr/src/redhat/SOURCES && \
rm -rf $BUILDDIR
cd /usr/src/redhat/ && \
rpm -ba SPECS/M.spec
mv RPMS/i386/$NAME*.rpm /home/karsten/WWW/Mahogany/daily/
mv SRPMS/$NAME*.rpm /home/karsten/WWW/Mahogany/daily/
