/*
 * FILE : ./MApplication.cpp
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 4)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/***********************************************************************
 * $Header$
 * swig_lib/python/python.cfg
 *
 * This file contains coded needed to add variable linking to the
 * Python interpreter.   C variables are added as a new kind of Python
 * datatype.
 *
 * Also contains supporting code for building python under Windows
 * and things like that.
 *
 * $Log$
 * Revision 1.2  1998/05/24 08:28:55  KB
 * eventually fixed the type problem, now python works as expected
 *
 ************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"
#ifdef __cplusplus
}
#endif

/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATIC PyObject *
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATIC void
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}



/*****************************************************************************
 * $Header$
 *
 * swigptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is typically used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer which is assumed to hold enough space for the result.
 *
 * char * SWIG_GetPtr(char *buffer, void **ptr, char *type)
 *
 *      Gets a pointer value from a string.  If there is a type-mismatch, returns
 *      a character string to the received type.  On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif


/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATIC 
char *SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start >= end) sp = 0;
	  /* Try to find a match for this */
	  if (sp) {
	    while (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strcpy(temp_type,tp->name);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	      sp++;
	      /* Hmmm. Didn't find it this time */
	    }
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

#define SWIG_init    initMApplicationc

#define SWIG_name    "MApplicationc"

#include	"Mpch.h"
#ifndef	USE_PCH
#	include	"Mcommon.h"
#	include	"strutil.h"
#	include	"Profile.h"
#	include	"MFrame.h"
#	include	"MLogFrame.h"
#	include	"MimeList.h"
#	include	"MimeTypes.h"
#	include	"Mdefaults.h"
#	include	"MApplication.h"
#endif
static int _wrap_mApplication_set(PyObject *val) {
    char * tval;
    MApplication * temp;

    tval = (char *) PyString_AsString(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'mApplication'(MApplication *)");
        return 1; 
    }
    if (tval) {
        if (SWIG_GetPtr(tval,(void **) &temp,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in value of mApplication. Expected _MApplication_p.");
        return 1;
        }
    }
    mApplication = *temp;
    return 0;
}

static PyObject *_wrap_mApplication_get() {
    PyObject * pyobj;
    char ptemp[128];

    SWIG_MakePtr(ptemp,(char *) &mApplication,"_MApplication_p");
    pyobj = PyString_FromString(ptemp);
    return pyobj;
}

#define new_MApplication() (new MApplication())
static PyObject *_wrap_new_MApplication(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MApplication * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":new_MApplication")) 
        return NULL;
    _result = (MApplication *)new_MApplication();
    SWIG_MakePtr(_ptemp, (char *) _result,"_MApplication_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define delete_MApplication(obj) (delete obj)
static PyObject *_wrap_delete_MApplication(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MApplication * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:delete_MApplication",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of delete_MApplication. Expected _MApplication_p.");
        return NULL;
        }
    }
    delete_MApplication(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define MApplication_Exit(obj,arg0)  (obj->Exit(arg0))
static PyObject *_wrap_MApplication_Exit(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MApplication * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:MApplication_Exit",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_Exit. Expected _MApplication_p.");
        return NULL;
        }
    }
    MApplication_Exit(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define MApplication_TopLevelFrame(obj)  (obj->TopLevelFrame())
static PyObject *_wrap_MApplication_TopLevelFrame(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MFrame * _result;
    MApplication * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:MApplication_TopLevelFrame",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_TopLevelFrame. Expected _MApplication_p.");
        return NULL;
        }
    }
    _result = (MFrame *)MApplication_TopLevelFrame(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_MFrame_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define MApplication_GetText(obj,arg0)  (obj->GetText(arg0))
static PyObject *_wrap_MApplication_GetText(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;
    MApplication * _arg0;
    char * _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"ss:MApplication_GetText",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_GetText. Expected _MApplication_p.");
        return NULL;
        }
    }
    _result = (char *)MApplication_GetText(_arg0,_arg1);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

#define MApplication_ErrorMessage(obj,arg0,arg1,arg2)  (obj->ErrorMessage(arg0,arg1,arg2))
static PyObject *_wrap_MApplication_ErrorMessage(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MApplication * _arg0;
    String * _arg1;
    MFrame * _arg2;
    bool  _arg3;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char * _argc2 = 0;
    int tempbool3;

    self = self;
    if(!PyArg_ParseTuple(args,"sssi:MApplication_ErrorMessage",&_argc0,&_argc1,&_argc2,&tempbool3)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_ErrorMessage. Expected _MApplication_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of MApplication_ErrorMessage. Expected _String_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_MFrame_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of MApplication_ErrorMessage. Expected _MFrame_p.");
        return NULL;
        }
    }
    _arg3 = (bool ) tempbool3;
    MApplication_ErrorMessage(_arg0,*_arg1,_arg2,_arg3);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define MApplication_SystemErrorMessage(obj,arg0,arg1,arg2)  (obj->SystemErrorMessage(arg0,arg1,arg2))
static PyObject *_wrap_MApplication_SystemErrorMessage(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MApplication * _arg0;
    String * _arg1;
    MFrame * _arg2;
    int  _arg3;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char * _argc2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sssi:MApplication_SystemErrorMessage",&_argc0,&_argc1,&_argc2,&_arg3)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_SystemErrorMessage. Expected _MApplication_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of MApplication_SystemErrorMessage. Expected _String_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_MFrame_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of MApplication_SystemErrorMessage. Expected _MFrame_p.");
        return NULL;
        }
    }
    MApplication_SystemErrorMessage(_arg0,*_arg1,_arg2,_arg3);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define MApplication_FatalErrorMessage(obj,arg0,arg1)  (obj->FatalErrorMessage(arg0,arg1))
static PyObject *_wrap_MApplication_FatalErrorMessage(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MApplication * _arg0;
    String * _arg1;
    MFrame * _arg2;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char * _argc2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sss:MApplication_FatalErrorMessage",&_argc0,&_argc1,&_argc2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_FatalErrorMessage. Expected _MApplication_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of MApplication_FatalErrorMessage. Expected _String_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_MFrame_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of MApplication_FatalErrorMessage. Expected _MFrame_p.");
        return NULL;
        }
    }
    MApplication_FatalErrorMessage(_arg0,*_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define MApplication_Message(obj,arg0,arg1,arg2)  (obj->Message(arg0,arg1,arg2))
static PyObject *_wrap_MApplication_Message(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MApplication * _arg0;
    String * _arg1;
    MFrame * _arg2;
    int  _arg3;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char * _argc2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sssi:MApplication_Message",&_argc0,&_argc1,&_argc2,&_arg3)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_Message. Expected _MApplication_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of MApplication_Message. Expected _String_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_MFrame_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of MApplication_Message. Expected _MFrame_p.");
        return NULL;
        }
    }
    MApplication_Message(_arg0,*_arg1,_arg2,_arg3);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define MApplication_YesNoDialog(obj,arg0,arg1,arg2,arg3)  (obj->YesNoDialog(arg0,arg1,arg2,arg3))
static PyObject *_wrap_MApplication_YesNoDialog(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    MApplication * _arg0;
    String * _arg1;
    MFrame * _arg2;
    int  _arg3;
    int  _arg4 = true;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char * _argc2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sssi|i:MApplication_YesNoDialog",&_argc0,&_argc1,&_argc2,&_arg3,&_arg4)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_YesNoDialog. Expected _MApplication_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of MApplication_YesNoDialog. Expected _String_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_MFrame_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of MApplication_YesNoDialog. Expected _MFrame_p.");
        return NULL;
        }
    }
    _result = (int )MApplication_YesNoDialog(_arg0,*_arg1,_arg2,_arg3,_arg4);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define MApplication_GetGlobalDir(obj)  (obj->GetGlobalDir())
static PyObject *_wrap_MApplication_GetGlobalDir(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    String * _result;
    MApplication * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:MApplication_GetGlobalDir",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_GetGlobalDir. Expected _MApplication_p.");
        return NULL;
        }
    }
    String & _result_ref = MApplication_GetGlobalDir(_arg0);
    _result = (String *) &_result_ref;
    SWIG_MakePtr(_ptemp, (char *) _result,"_String_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define MApplication_GetLocalDir(obj)  (obj->GetLocalDir())
static PyObject *_wrap_MApplication_GetLocalDir(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    String * _result;
    MApplication * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:MApplication_GetLocalDir",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_GetLocalDir. Expected _MApplication_p.");
        return NULL;
        }
    }
    String & _result_ref = MApplication_GetLocalDir(_arg0);
    _result = (String *) &_result_ref;
    SWIG_MakePtr(_ptemp, (char *) _result,"_String_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define MApplication_GetMimeList(obj)  (obj->GetMimeList())
static PyObject *_wrap_MApplication_GetMimeList(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MimeList * _result;
    MApplication * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:MApplication_GetMimeList",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_GetMimeList. Expected _MApplication_p.");
        return NULL;
        }
    }
    _result = (MimeList *)MApplication_GetMimeList(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_MimeList_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define MApplication_GetMimeTypes(obj)  (obj->GetMimeTypes())
static PyObject *_wrap_MApplication_GetMimeTypes(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MimeTypes * _result;
    MApplication * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:MApplication_GetMimeTypes",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_GetMimeTypes. Expected _MApplication_p.");
        return NULL;
        }
    }
    _result = (MimeTypes *)MApplication_GetMimeTypes(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_MimeTypes_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define MApplication_GetProfile(obj)  (obj->GetProfile())
static PyObject *_wrap_MApplication_GetProfile(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    ProfileBase * _result;
    MApplication * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:MApplication_GetProfile",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_GetProfile. Expected _MApplication_p.");
        return NULL;
        }
    }
    _result = (ProfileBase *)MApplication_GetProfile(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_ProfileBase_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define MApplication_GetAdb(obj)  (obj->GetAdb())
static PyObject *_wrap_MApplication_GetAdb(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Adb * _result;
    MApplication * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:MApplication_GetAdb",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_GetAdb. Expected _MApplication_p.");
        return NULL;
        }
    }
    _result = (Adb *)MApplication_GetAdb(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_Adb_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define MApplication_ShowConsole(obj,arg0)  (obj->ShowConsole(arg0))
static PyObject *_wrap_MApplication_ShowConsole(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MApplication * _arg0;
    int  _arg1 = true;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s|i:MApplication_ShowConsole",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_ShowConsole. Expected _MApplication_p.");
        return NULL;
        }
    }
    MApplication_ShowConsole(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define MApplication_Log(obj,arg0,arg1)  (obj->Log(arg0,arg1))
static PyObject *_wrap_MApplication_Log(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    MApplication * _arg0;
    int  _arg1;
    String * _arg2;
    char * _argc0 = 0;
    char * _argc2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sis:MApplication_Log",&_argc0,&_arg1,&_argc2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_MApplication_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of MApplication_Log. Expected _MApplication_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of MApplication_Log. Expected _String_p.");
        return NULL;
        }
    }
    MApplication_Log(_arg0,_arg1,*_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyMethodDef MApplicationcMethods[] = {
	 { "MApplication_Log", _wrap_MApplication_Log, 1 },
	 { "MApplication_ShowConsole", _wrap_MApplication_ShowConsole, 1 },
	 { "MApplication_GetAdb", _wrap_MApplication_GetAdb, 1 },
	 { "MApplication_GetProfile", _wrap_MApplication_GetProfile, 1 },
	 { "MApplication_GetMimeTypes", _wrap_MApplication_GetMimeTypes, 1 },
	 { "MApplication_GetMimeList", _wrap_MApplication_GetMimeList, 1 },
	 { "MApplication_GetLocalDir", _wrap_MApplication_GetLocalDir, 1 },
	 { "MApplication_GetGlobalDir", _wrap_MApplication_GetGlobalDir, 1 },
	 { "MApplication_YesNoDialog", _wrap_MApplication_YesNoDialog, 1 },
	 { "MApplication_Message", _wrap_MApplication_Message, 1 },
	 { "MApplication_FatalErrorMessage", _wrap_MApplication_FatalErrorMessage, 1 },
	 { "MApplication_SystemErrorMessage", _wrap_MApplication_SystemErrorMessage, 1 },
	 { "MApplication_ErrorMessage", _wrap_MApplication_ErrorMessage, 1 },
	 { "MApplication_GetText", _wrap_MApplication_GetText, 1 },
	 { "MApplication_TopLevelFrame", _wrap_MApplication_TopLevelFrame, 1 },
	 { "MApplication_Exit", _wrap_MApplication_Exit, 1 },
	 { "delete_MApplication", _wrap_delete_MApplication, 1 },
	 { "new_MApplication", _wrap_new_MApplication, 1 },
	 { NULL, NULL }
};
static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void,initMApplicationc)() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("MApplicationc", MApplicationcMethods);
	 d = PyModule_GetDict(m);
	 PyDict_SetItemString(d,"cvar", SWIG_globals);
	 SWIG_addvarlink(SWIG_globals,"mApplication",_wrap_mApplication_get, _wrap_mApplication_set);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_MApplication","_class_MApplication",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_class_MApplication","_MApplication",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_String","_class_String",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
	 SWIG_RegisterMapping("_class_String","_String",0);
}
