/*
 * FILE : ./Profile.cpp
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1  (Final)
 * 
 * Portions Copyright (c) 1995-1997
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define EXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define EXPORT(a,b) a _export b
#	else
#	    define EXPORT(a,b) a b
#	endif
#   endif
#else
#   define EXPORT(a,b) a b
#endif

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"
extern void SWIG_MakePtr(char *, void *, char *);
extern void SWIG_RegisterMapping(char *, char *, void *(*)(void *));
extern char *SWIG_GetPtr(char *, void **, char *);
extern void SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
extern PyObject *SWIG_newvarlink(void);
#ifdef __cplusplus
}
#endif

#define SWIG_init    initMProfilec

#define SWIG_name    "MProfilec"

#include  "Mcommon.h"
#include  "Profile.h"

// we don't want to export our functions as we don't build a shared library
#undef SWIGEXPORT
#define SWIGEXPORT(a,b) a b
static void *SwigProfileBaseToMObjectRC(void *ptr) {
    ProfileBase *src;
    MObjectRC *dest;
    src = (ProfileBase *) ptr;
    dest = (MObjectRC *) src;
    return (void *) dest;
}

static void *SwigProfileBaseToMObject(void *ptr) {
    ProfileBase *src;
    MObject *dest;
    src = (ProfileBase *) ptr;
    dest = (MObject *) src;
    return (void *) dest;
}

static PyObject *_wrap_ProfileBase_CreateProfile(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    ProfileBase * _result;
    String * _arg0;
    ProfileBase * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char _ptemp[128];

    if(!PyArg_ParseTuple(args,"ss:ProfileBase_CreateProfile",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_CreateProfile. Expected _String_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_ProfileBase_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of ProfileBase_CreateProfile. Expected _ProfileBase_p.");
        return NULL;
        }
    }
    _result = (ProfileBase *)ProfileBase::CreateProfile(*_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (char *) _result,"_ProfileBase_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_ProfileBase_CreateGlobalConfig(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    ProfileBase * _result;
    String * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    if(!PyArg_ParseTuple(args,"s:ProfileBase_CreateGlobalConfig",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_CreateGlobalConfig. Expected _String_p.");
        return NULL;
        }
    }
    _result = (ProfileBase *)ProfileBase::CreateGlobalConfig(*_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_ProfileBase_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static String  ProfileBase_readEntry(ProfileBase *obj,String * _arg0,char * _arg1) {
    String  _result = (String )obj->readEntry(*_arg0,_arg1);
    return _result;
}
static PyObject *_wrap_ProfileBase_readEntry(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    String * _result;
    ProfileBase * _arg0;
    String * _arg1;
    char * _arg2;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char _ptemp[128];

    if(!PyArg_ParseTuple(args,"sss:ProfileBase_readEntry",&_argc0,&_argc1,&_arg2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_ProfileBase_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_readEntry. Expected _ProfileBase_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of ProfileBase_readEntry. Expected _String_p.");
        return NULL;
        }
    }
    _result = new String (ProfileBase_readEntry(_arg0,_arg1,_arg2));
    SWIG_MakePtr(_ptemp, (void *) _result,"_String_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static bool  ProfileBase_writeEntry(ProfileBase *obj,String * _arg0,String * _arg1) {
    bool  _result = (bool )obj->writeEntry(*_arg0,*_arg1);
    return _result;
}
static PyObject *_wrap_ProfileBase_writeEntry(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    ProfileBase * _arg0;
    String * _arg1;
    String * _arg2;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char * _argc2 = 0;

    if(!PyArg_ParseTuple(args,"sss:ProfileBase_writeEntry",&_argc0,&_argc1,&_argc2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_ProfileBase_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_writeEntry. Expected _ProfileBase_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of ProfileBase_writeEntry. Expected _String_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of ProfileBase_writeEntry. Expected _String_p.");
        return NULL;
        }
    }
    _result = (bool )ProfileBase_writeEntry(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static void  ProfileBase_SetPath(ProfileBase *obj,String * _arg0) {
    obj->SetPath(*_arg0);
}
static PyObject *_wrap_ProfileBase_SetPath(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    ProfileBase * _arg0;
    String * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;

    if(!PyArg_ParseTuple(args,"ss:ProfileBase_SetPath",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_ProfileBase_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_SetPath. Expected _ProfileBase_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of ProfileBase_SetPath. Expected _String_p.");
        return NULL;
        }
    }
    ProfileBase_SetPath(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static String  ProfileBase_GetPath(ProfileBase *obj) {
    String  _result = (String )obj->GetPath();
    return _result;
}
static PyObject *_wrap_ProfileBase_GetPath(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    String * _result;
    ProfileBase * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    if(!PyArg_ParseTuple(args,"s:ProfileBase_GetPath",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_ProfileBase_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_GetPath. Expected _ProfileBase_p.");
        return NULL;
        }
    }
    _result = new String (ProfileBase_GetPath(_arg0));
    SWIG_MakePtr(_ptemp, (void *) _result,"_String_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static bool  ProfileBase_HasEntry(ProfileBase *obj,String * _arg0) {
    bool  _result = (bool )obj->HasEntry(*_arg0);
    return _result;
}
static PyObject *_wrap_ProfileBase_HasEntry(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    ProfileBase * _arg0;
    String * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;

    if(!PyArg_ParseTuple(args,"ss:ProfileBase_HasEntry",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_ProfileBase_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_HasEntry. Expected _ProfileBase_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of ProfileBase_HasEntry. Expected _String_p.");
        return NULL;
        }
    }
    _result = (bool )ProfileBase_HasEntry(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static void  ProfileBase_DeleteGroup(ProfileBase *obj,String * _arg0) {
    obj->DeleteGroup(*_arg0);
}
static PyObject *_wrap_ProfileBase_DeleteGroup(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    ProfileBase * _arg0;
    String * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;

    if(!PyArg_ParseTuple(args,"ss:ProfileBase_DeleteGroup",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_ProfileBase_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_DeleteGroup. Expected _ProfileBase_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_String_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of ProfileBase_DeleteGroup. Expected _String_p.");
        return NULL;
        }
    }
    ProfileBase_DeleteGroup(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static String  ProfileBase_GetProfileName(ProfileBase *obj) {
    String  _result = (String )obj->GetProfileName();
    return _result;
}
static PyObject *_wrap_ProfileBase_GetProfileName(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    String * _result;
    ProfileBase * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    if(!PyArg_ParseTuple(args,"s:ProfileBase_GetProfileName",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_ProfileBase_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_GetProfileName. Expected _ProfileBase_p.");
        return NULL;
        }
    }
    _result = new String (ProfileBase_GetProfileName(_arg0));
    SWIG_MakePtr(_ptemp, (void *) _result,"_String_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static bool  ProfileBase_IsExpandingEnvVars(ProfileBase *obj) {
    bool  _result = (bool )obj->IsExpandingEnvVars();
    return _result;
}
static PyObject *_wrap_ProfileBase_IsExpandingEnvVars(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    ProfileBase * _arg0;
    char * _argc0 = 0;

    if(!PyArg_ParseTuple(args,"s:ProfileBase_IsExpandingEnvVars",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_ProfileBase_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_IsExpandingEnvVars. Expected _ProfileBase_p.");
        return NULL;
        }
    }
    _result = (bool )ProfileBase_IsExpandingEnvVars(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static void  ProfileBase_SetExpandEnvVars(ProfileBase *obj,bool  _arg0) {
    obj->SetExpandEnvVars(_arg0);
}
static PyObject *_wrap_ProfileBase_SetExpandEnvVars(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    ProfileBase * _arg0;
    bool  _arg1 = TRUE;
    char * _argc0 = 0;

    if(!PyArg_ParseTuple(args,"s|i:ProfileBase_SetExpandEnvVars",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_ProfileBase_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of ProfileBase_SetExpandEnvVars. Expected _ProfileBase_p.");
        return NULL;
        }
    }
    ProfileBase_SetExpandEnvVars(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyMethodDef MProfilecMethods[] = {
	 { "ProfileBase_SetExpandEnvVars", _wrap_ProfileBase_SetExpandEnvVars, 1 },
	 { "ProfileBase_IsExpandingEnvVars", _wrap_ProfileBase_IsExpandingEnvVars, 1 },
	 { "ProfileBase_GetProfileName", _wrap_ProfileBase_GetProfileName, 1 },
	 { "ProfileBase_DeleteGroup", _wrap_ProfileBase_DeleteGroup, 1 },
	 { "ProfileBase_HasEntry", _wrap_ProfileBase_HasEntry, 1 },
	 { "ProfileBase_GetPath", _wrap_ProfileBase_GetPath, 1 },
	 { "ProfileBase_SetPath", _wrap_ProfileBase_SetPath, 1 },
	 { "ProfileBase_writeEntry", _wrap_ProfileBase_writeEntry, 1 },
	 { "ProfileBase_readEntry", _wrap_ProfileBase_readEntry, 1 },
	 { "ProfileBase_CreateGlobalConfig", _wrap_ProfileBase_CreateGlobalConfig, 1 },
	 { "ProfileBase_CreateProfile", _wrap_ProfileBase_CreateProfile, 1 },
	 { NULL, NULL }
};
static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
EXPORT(void,initMProfilec)() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("MProfilec", MProfilecMethods);
	 d = PyModule_GetDict(m);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_ProfileBase","_class_ProfileBase",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_MObject","_class_ProfileBase",SwigProfileBaseToMObject);
	 SWIG_RegisterMapping("_MObject","_ProfileBase",SwigProfileBaseToMObject);
	 SWIG_RegisterMapping("_MObject","_class_MObject",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_MObjectRC","_class_ProfileBase",SwigProfileBaseToMObjectRC);
	 SWIG_RegisterMapping("_MObjectRC","_ProfileBase",SwigProfileBaseToMObjectRC);
	 SWIG_RegisterMapping("_MObjectRC","_class_MObjectRC",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_class_ProfileBase","_ProfileBase",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_String","_class_String",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
	 SWIG_RegisterMapping("_class_MObjectRC","_class_ProfileBase",SwigProfileBaseToMObjectRC);
	 SWIG_RegisterMapping("_class_MObjectRC","_ProfileBase",SwigProfileBaseToMObjectRC);
	 SWIG_RegisterMapping("_class_MObjectRC","_MObjectRC",0);
	 SWIG_RegisterMapping("_class_MObject","_class_ProfileBase",SwigProfileBaseToMObject);
	 SWIG_RegisterMapping("_class_MObject","_ProfileBase",SwigProfileBaseToMObject);
	 SWIG_RegisterMapping("_class_MObject","_MObject",0);
	 SWIG_RegisterMapping("_class_String","_String",0);
}
