  mail_link (&imapdriver);	/* link in the imap driver */
  mail_link (&nntpdriver);	/* link in the nntp driver */
  mail_link (&pop3driver);	/* link in the pop3 driver */
  mail_link (&mbxdriver);	/* link in the mbx driver */
  mail_link (&mtxdriver);	/* link in the mtx driver */
  mail_link (&tenexdriver);	/* link in the tenex driver */
  mail_link (&unixdriver);	/* link in the unix driver */
  mail_link (&dummydriver);	/* link in the dummy driver */
  auth_link (&auth_ext);		/* link in the ext authenticator */
  auth_link (&auth_md5);		/* link in the md5 authenticator */
  auth_link (&auth_pla);		/* link in the pla authenticator */
  auth_link (&auth_log);		/* link in the log authenticator */
