# Makefile for extra/install/scripts directory

CWD = scripts

include ../../../makeopts

#
# install the contents of all subdirs under this one
#
install:
	$(INSTALL_PROGRAM) Mnetscape $(BINDIR)

include ../../../makerules

.PHONY: install
