#!/bin/sh
#
# Copyright (C) 1998 by Karsten Ballüder <Ballueder@usa.net>
#
# $Id$
#
#This is a script to run netscape from within M

netscape -remote "openURL($1)" || \
	netscape $1

# alternatively you can supply openURL($1,new-window) to open a new window