.\".\" $Id$
.\"
.Dd September, 2000
.Dt MAHOGANY 1
.Os "Linux"
.Sh NAME
.Nm mahogany
.Nd mail and news client with X11 interface
.Sh SYNOPSIS
.Nm mahogany
.Sh DESCRIPTION
.Nm Mahogany
is an email and news client for Unix and MS Windows, featuring a rich
set of features including powerful filter rules, an embedded Python
interpreter for extensibility, loadable extension modules and full
POP3 and IMAP support.
.br
More information is available in the online manual accessible from
within the application.
.Sh AUTHORS
Original authors are Karsten Ballüder and Vadim Zeitlin.
.br
Now maintained and developed by a team of volunteers.
.Sh FURTHER INFORMATION
.br
See http://mahogany.sourceforge.net/ for more information and user
support mailing lists.
