///////////////////////////////////////////////////////////////////////////////
// Project:     M - cross platform e-mail GUI client
// File name:   include/MpersIds.h
// Purpose:     all persistent message box ids
// Author:      Vadim Zeitlin
// Modified by:
// Created:     06.03.02
// CVS-ID:      $Id$
// Copyright:   (c) 2002 Vadim Zeitlin <zeitlin@dptmaths.ens-cachan.fr>
// Licence:     M license
///////////////////////////////////////////////////////////////////////////////

// this file is not intended to be included by any other files except Mpers.cpp
#ifndef DECL_OR_DEF
   #error "This file should not be included!"
#endif

// the order of declarations/definitions of the MPersMsgBox objects and the
// array in Mpers.cpp must be kept in sync!
DECL_OR_DEF MPersMsgBox M_MSGBOX_ASK_SPECIFY_DIR;
#ifdef OS_UNIX
DECL_OR_DEF MPersMsgBox M_MSGBOX_ASK_RUNASROOT;
#endif
DECL_OR_DEF MPersMsgBox M_MSGBOX_SEND_OUTBOX_ON_EXIT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_ABANDON_CRITICAL;
DECL_OR_DEF MPersMsgBox M_MSGBOX_GO_ONLINE_TO_SEND_OUTBOX;
DECL_OR_DEF MPersMsgBox M_MSGBOX_FIX_TEMPLATE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_ASK_FOR_SIG;
DECL_OR_DEF MPersMsgBox M_MSGBOX_UNSAVED_PROMPT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_MESSAGE_SENT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_ASK_FOR_EXT_EDIT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_MIME_TYPE_CORRECT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_CONFIG_NET_FROM_COMPOSE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_SEND_EMPTY_SUBJECT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_CONFIRM_FOLDER_REMOVE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_CONFIRM_FOLDER_DELETE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_MARK_READ;
#ifdef USE_DIALUP
DECL_OR_DEF MPersMsgBox M_MSGBOX_DIALUP_CONNECTED_MSG;
DECL_OR_DEF MPersMsgBox M_MSGBOX_DIALUP_DISCONNECTED_MSG;
DECL_OR_DEF MPersMsgBox M_MSGBOX_DIALUP_ON_OPEN_FOLDER;
DECL_OR_DEF MPersMsgBox M_MSGBOX_NET_DOWN_OPEN_ANYWAY;
DECL_OR_DEF MPersMsgBox M_MSGBOX_NO_NET_PING_ANYWAY;
#endif // USE_DIALUP
DECL_OR_DEF MPersMsgBox M_MSGBOX_CONFIRM_EXIT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_ASK_LOGIN;
DECL_OR_DEF MPersMsgBox M_MSGBOX_ASK_PWD;
DECL_OR_DEF MPersMsgBox M_MSGBOX_GO_OFFLINE_SEND_FIRST;
DECL_OR_DEF MPersMsgBox M_MSGBOX_OPEN_UNACCESSIBLE_FOLDER;
DECL_OR_DEF MPersMsgBox M_MSGBOX_CHANGE_UNACCESSIBLE_FOLDER_SETTINGS;
DECL_OR_DEF MPersMsgBox M_MSGBOX_ASK_URL_BROWSER;
DECL_OR_DEF MPersMsgBox M_MSGBOX_OPT_TEST_ASK;
DECL_OR_DEF MPersMsgBox M_MSGBOX_WARN_RESTART_OPT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_SAVE_TEMLPATE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_MAIL_NO_NET_QUEUED_MESSAGE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_MAIL_QUEUED_MESSAGE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_MAIL_SENT_MESSAGE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_TEST_MAIL_SENT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_ADB_DELETE_ENTRY;
DECL_OR_DEF MPersMsgBox M_MSGBOX_CONFIRM_ADB_IMPORTER;
DECL_OR_DEF MPersMsgBox M_MSGBOX_MODULES_WARNING;
DECL_OR_DEF MPersMsgBox M_MSGBOX_BBDB_SAVE_DIALOG;
DECL_OR_DEF MPersMsgBox M_MSGBOX_FOLDER_GROUP_HINT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_SIGNATURE_LENGTH;
DECL_OR_DEF MPersMsgBox M_MSGBOX_REMEMBER_PWD;
DECL_OR_DEF MPersMsgBox M_MSGBOX_KEEP_PWD;
DECL_OR_DEF MPersMsgBox M_MSGBOX_SHOWLOGWINHINT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_AUTOEXPUNGE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_SUSPENDAUTOCOLLECT;
#if 0
DECL_OR_DEF MPersMsgBox M_MSGBOX_RULESMISMATCHWARN1;
DECL_OR_DEF MPersMsgBox M_MSGBOX_RULESMISMATCHWARN2;
#endif
DECL_OR_DEF MPersMsgBox M_MSGBOX_FILTER_REPLACE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_ADD_ALL_SUBFOLDERS;

DECL_OR_DEF MPersMsgBox M_MSGBOX_OPT_STOREREMOTENOW;
DECL_OR_DEF MPersMsgBox M_MSGBOX_OPT_GETREMOTENOW;
DECL_OR_DEF MPersMsgBox M_MSGBOX_OVERWRITE_REMOTE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_RETRIEVE_REMOTE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_STORE_REMOTE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_CONFIG_SAVED_REMOTELY;

DECL_OR_DEF MPersMsgBox M_MSGBOX_EXPLAIN_GLOBALPASSWD;
DECL_OR_DEF MPersMsgBox M_MSGBOX_FILTER_NOT_USED_YET;
DECL_OR_DEF MPersMsgBox M_MSGBOX_FILTER_CONFIRM_OVERWRITE;
DECL_OR_DEF MPersMsgBox M_MSGBOX_IMPORT_FOLDERS_UNDER_ROOT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_MOVE_EXPUNGE_CONFIRM;
DECL_OR_DEF MPersMsgBox M_MSGBOX_APPLY_QUICK_FILTER_NOW;
DECL_OR_DEF MPersMsgBox M_MSGBOX_BROWSE_IMAP_SERVERS;
DECL_OR_DEF MPersMsgBox M_MSGBOX_GFX_NOT_INLINED;
DECL_OR_DEF MPersMsgBox M_MSGBOX_EDIT_FOLDER_ON_OPEN_FAIL;
DECL_OR_DEF MPersMsgBox M_MSGBOX_EXPLAIN_COLUMN_CLICK;
DECL_OR_DEF MPersMsgBox M_MSGBOX_VIEWER_BAR_TIP;

DECL_OR_DEF MPersMsgBox M_MSGBOX_EMPTY_TRASH_ON_EXIT;
DECL_OR_DEF MPersMsgBox M_MSGBOX_SEND_OFFLINE;

DECL_OR_DEF MPersMsgBox M_MSGBOX_MAX;

