///////////////////////////////////////////////////////////////////////////////
// Project:     M
// File name:   Mswig.h - header to be included by all SWIG modules
// Purpose:     there are some common compilation settings which should be
//              used for all .cpp files generated by SWIG
// Author:      Vadim Zeitlin
// Modified by:
// Created:     08.03.01
// CVS-ID:      $Id$
// Copyright:   (c) 2001 Vadim Zeitlin <zeitlin@dptmaths.ens-cachan.fr>
// Licence:     M license
///////////////////////////////////////////////////////////////////////////////

#ifndef _MSWIG_H_
#define _MSWIG_H_

#include <wx/defs.h>

#include "Mconfig.h"

// disable some warnings which VC++ gives for swig-generated code
#ifdef __VISUALC__
   // 'int' : forcing value to bool 'true' or 'false' (performance warning)
   #pragma warning(disable:4800)
#endif // VC++

#endif // _MSWIG_H_
