name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      # This is needed for ccache to work with the precompiled header used by
      # this build, see the comment for CPPFLAGS below.
      CCACHE_SLOPPINESS: pch_defines,time_macros
    steps:
    - uses: actions/checkout@v7
    - name: Bootstrap
      run: ./bootstrap
    - name: Install wxWidgets
      id: wx
      uses: mamba-org/setup-micromamba@v3
      with:
        environment-name: wxenv
        create-args: -c conda-forge wxwidgets
        init-shell: none
        cache-downloads: true
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2.24
      with:
        key: ${{ github.job }}
        evict-old-files: job
    - name: Configure
      run: |
        mkdir build-autoconf
        cd build-autoconf
        # -fpch-preprocess is required by ccache when using precompiled
        # headers included using #include, as we do.
        ../configure CC="ccache gcc" CXX="ccache g++" \
                     CPPFLAGS=-fpch-preprocess \
                     --with-wx-config=${{ steps.wx.outputs.environment-path }}/bin/wx-config
    - name: Build
      run: |
        make -j"$(nproc)" -C build-autoconf

  build-linux-cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install wxWidgets
      id: wx
      uses: mamba-org/setup-micromamba@v3
      with:
        environment-name: wxenv
        create-args: -c conda-forge wxwidgets
        init-shell: none
        cache-downloads: true
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2.24
      with:
        key: ${{ github.job }}
        evict-old-files: job
    - name: Configure
      run: |
        cmake -S . -B build-cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DWX_CONFIG=${{ steps.wx.outputs.environment-path }}/bin/wx-config \
              -DOPENSSL_ROOT_DIR=${{ steps.wx.outputs.environment-path }}
    - name: Build
      run: |
        ninja -C build-cmake

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v3
    - name: Install wxWidgets
      id: wx
      uses: mamba-org/setup-micromamba@v3
      with:
        environment-name: wxenv
        create-args: -c conda-forge wxwidgets
        init-shell: none
        cache-downloads: true
    - name: Build
      env:
        WXWIN: '${{ steps.wx.outputs.environment-path }}\Library'
      run: msbuild.exe -noLogo -maxCpuCount -property:"Platform=x64,Configuration=Release DLL" M.sln

  build-windows-cmake:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install wxWidgets
      id: wx
      uses: mamba-org/setup-micromamba@v3
      with:
        environment-name: wxenv
        create-args: -c conda-forge wxwidgets
        init-shell: none
        cache-downloads: true
    - name: Configure
      env:
        WXWIN: '${{ steps.wx.outputs.environment-path }}\Library'
      run: |
        cmake -S . -B build-cmake
    - name: Build
      run: |
        cmake --build build-cmake --config Release
